[workspace]
resolver = "2"
members = [
    "cli",
    "libs/git-proxy",
    "libs/git-proxy/examples/basic-remote",
    "libs/git-proxy/examples/basic-local",
    "libs/agent-api",
    "libs/llm-proxy",
]
